### ISSUE TITLE
M_nk() Loop Dimension Mismatch

### ISSUE THREAD

**Issue by snowneji** [zjelveh/learning-fair-representations#2]
In `distances()` function, the output: `dists = np.zeros((N, P)` has dimension of `(N,P)`

However, the next step in `M_nk()` function, we are trying to loop until `k` dimensions column-wise not `P`, which didn't loop all of the `dists` columns, is this a bug?

    for i in range(N):
        for j in range(k):
            exp[i, j] = np.exp(-1 * dists[i, j])

**Comment by zjelveh** [comment]
It's a been a few years since I looked at this, but rereading the paper, I believe you are correct. Would be much appreciated if you could create a pull request.

**Comment by zjelveh** [comment]
I pushed a fixed to the [fix_Mnk_function](/zjelveh/learning-fair-representations/tree/fix_Mnk_function) branch. Needs to be tested.

**Comment by shangwen777** [comment]
I think the the dimention of the dists initialization matrix in the distance function is not correct. dist should be (N, k) instead of (N, P). So all the columns of dists from k+1 to P are zeros, however M_nk only loops columns from 1 to k, which is correct. This issue doesn't affect the final results.
